// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Infrastructure.Data;

namespace Web.Migrations
{
    [DbContext(typeof(PinDataContext))]
    partial class PinDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Models.PinNumber", b =>
                {
                    b.Property<string>("Pin")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Consumed");

                    b.HasKey("Pin");

                    b.ToTable("PinNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
